name: PersonalFinanceTracker
options:
  bundleIdPrefix: ${BUNDLE_PREFIX}
  deploymentTarget:
    iOS: '17.0'
settings:
      base:
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ${MY_DEVELOPMENT_TEAM}
        GENERATE_INFOPLIST_FILE: YES
        INFO_PLIST_FILE: PersonalFinanceTracker/Info.plist
        IOS_DEPLOYMENT_TARGET: '17.0'
targets:
  PersonalFinanceTracker:
    type: application
    platform: iOS
    sources: 
      - PersonalFinanceTracker
      
