name: PersonalFinanceTracker
options:
  bundleIdPrefix: ${BUNDLE_PREFIX}
settings:
      base:
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ${MY_DEVELOPMENT_TEAM}
        GENERATE_INFOPLIST_FILE: YES
        INFO_PLIST_FILE: PersonalFinanceTracker/Info.plist
targets:
  PersonalFinanceTracker:
    type: application
    platform: iOS
    deploymentTarget: '17.0'
    scheme: {}
    sources: 
      - PersonalFinanceTracker
parallelizeBuild: true