name: PersonalFinanceTracker
options:
  bundleIdPrefix: ${BUNDLE_PREFIX}
  deploymentTarget:
    iOS: '17.0'
    macOS: '14.4'
settings:
      base:
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ${MY_DEVELOPMENT_TEAM}
        GENERATE_INFOPLIST_FILE: YES
        INFO_PLIST_FILE: PersonalFinanceTracker/Info.plist
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
configs:
  Development Debug: debug
  Development Release: release
targets:
  PersonalFinanceTracker:
    type: application
    platform: iOS
    supportedDestinations: [iOS, macOS]
    sources: 
      - PersonalFinanceTracker
    scheme:
      configVariants:
        - Development

parallelizeBuild: true